spring.application.name=btech

# Porta dinamica (Render injeta via variavel PORT)
server.port=${PORT:8080}

# Supabase / PostgreSQL
spring.datasource.url=jdbc:postgresql://db.qjpjbgjujiojzqdnifwq.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Navios@28btech.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect